name: Android Play Store Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      PLAY_STORE_JSON: ${{ secrets.PLAY_STORE_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          echo "$SIGNING_KEY" | base64 -d > my-release-key.jks
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.jks \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS

      - name: Zipalign APK
        run: |
          $ANDROID_HOME/build-tools/30.0.3/zipalign -v -p 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app/build/outputs/apk/release/app-release-aligned.apk

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.PLAY_STORE_JSON }}
          packageName: com.example.myapp
          releaseFiles: app/build/outputs/apk/release/app-release-aligned.apk
          track: beta
          inAppUpdatePriority: 3
