name: Android CI/CD Pipeline

on:
  push:
    branches:
      - Pre-Production

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Run Android Tests
        run: ./gradlew test --no-daemon

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4   
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  upload:
    runs-on: ubuntu-latest
    needs: build
    name: Upload APK to Firebase

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Download built APK
        uses: actions/download-artifact@v4   
        with:
          name: release-apk

      - name: Check APK Path
        run: |
          echo "Checking APK path"
          ls -l

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups "Testers" \
            --debug
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
