name: Android CI/CD Pipeline

on:
  push:
    branches:
      - Pre-Production

permissions:
  contents: read
  id-token: write  # Required for Firebase authentication

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew :app:assembleRelease --no-daemon

      - name: Debug APK Paths
        run: ls -R app/build/outputs/apk/

      - name: Verify Unsigned APK Exists
        run: ls app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Create Release Notes
        run: echo "New Pre-Production build $(date)" > release_notes.txt

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  distribute:
    runs-on: ubuntu-latest
    needs: build
    name: Distribute to Firebase

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-unsigned

      - name: Rename APK for Clarity
        run: mv app-release-unsigned.apk app-preprod-release.apk

      - name: Distribute via Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: app-preprod-release.apk
          releaseNotesFile: release_notes.txt
