name: Android CI/CD Pipeline

on:
  push:
    branches:
      - Pre-Production

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew :app:assembleRelease --no-daemon

      - name: Run Android Tests
        run: ./gradlew :app:test --no-daemon

      - name: Check APK Exists
        run: ls app/build/outputs/apk/release/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

  upload:
    runs-on: ubuntu-latest
    needs: build
    name: Upload APK to Firebase

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk

      - name: Validate APK Exists
        run: |
          if [ ! -f app-release.apk ]; then
            echo "::error::APK file missing!"
            exit 1
          fi

      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: app-release.apk
          releaseNotes: "New Pre-Production build"
