name: iOS CI/CD Pipeline - Pre-Production

on:
  push:
    branches:
      - Pre-Production
  pull_request:
    branches:
      - Pre-Production

jobs:
  build:
    name: Build and Deploy iOS App (Pre-Production)
    runs-on: macos-latest

    steps:
      - name: Check Git Commit Status
        run: echo "Checking commit status (placeholder for real tests)."

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Configure Credentials
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          echo "Configured Apple credentials from GitHub Secrets."

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -sdk iphoneos \
            -configuration Release

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          bundle exec fastlane pilot upload

      - name: Send Deployment Notification (Optional)
        run: echo "Deployment completed. (Configure real email notifications if needed.)"
