name: Android CI/CD Pipeline

on:
  push:
    branches:
      - Pre-Production

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Run Android Tests
        run: ./gradlew test --no-daemon

      - name: Check if APK Exists
        run: |
          echo "Checking APK existence..."
          ls -l app/build/outputs/apk/release/

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 7
